import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GameProvider } from "./Context/GameContext";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Betting on TC",
  description: "Generated by create next app",
   icons: {
    icon: '/439.webp',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GameProvider>{children}</GameProvider>

      </body>
    </html>
  );
}
